### ISSUE TITLE
Another installation error

### ISSUE THREAD

**Issue by ekazakos** [ROCmSoftwarePlatform/flash-attention#36]
Hi,

I'm trying to install the library but I have PyTorch with ROCm support in my conda environment so I'm not using the recommended docker. In particular in my conda env I have PyTorch 2.0.1 with ROCm 4.5.2 (the pre-built one provided by PyTorch). I have tested and in my cluster `torch.cuda.is_available()` returns `True`. Since the cluster has MI250 GPUs, I have set `export GPU_ARCHS="gfx90a"`. Pip installation fails with (pasting only the tail of the error as it is huge):

```
In file included from /pfs/lustrep4/users/kazakose/flash-attention/csrc/flash_attn_rocm/src/flash_bwd_runner_grouped_hdim128_bf16_noncausal_gfx9x_hip.hip:24:
      In file included from /pfs/lustrep4/users/kazakose/flash-attention/csrc/flash_attn_rocm/src/flash_runner_hip.hpp:27:
      In file included from /pfs/lustrep4/users/kazakose/flash-attention/csrc/flash_attn_rocm/src/bwd_device_gemm_invoker_hip.hpp:27:
      In file included from /pfs/lustrep4/users/kazakose/flash-attention/csrc/flash_attn_rocm/src/bwd_device_gemm_template_hip.hpp:27:
      In file included from /pfs/lustrep4/users/kazakose/flash-attention/csrc/flash_attn_rocm/src/device_gemm_trait_hip.hpp:27:
      In file included from /pfs/lustrep4/users/kazakose/flash-attention/csrc/flash_attn_rocm/src/params_hip.hpp:30:
      In file included from /pfs/lustrep4/users/kazakose/flash-attention/csrc/flash_attn_rocm/src/utils_hip.hpp:36:
      In file included from /project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/include/torch/extension.h:6:
      In file included from /project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/python.h:11:
      In file included from /project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/include/torch/csrc/Exceptions.h:14:
      In file included from /project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/include/pybind11/pybind11.h:13:
      In file included from /project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/include/pybind11/detail/class.h:12:
      In file included from /project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/include/pybind11/detail/../attr.h:13:
      /project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/include/pybind11/detail/common.h:587:7: error: no member named 'remove_cvref_t' in namespace 'std'; did you mean 'thrust::remove_cvref_t'?
      using std::remove_cvref_t;
            ^~~~~~~~~~~~~~~~~~~
            thrust::remove_cvref_t
      /appl/lumi/SW/CrayEnv/EB/rocm/5.6.1/include/thrust/type_traits/remove_cvref.h:87:1: note: 'thrust::remove_cvref_t' declared here
      using remove_cvref_t = typename remove_cvref<T>::type;
      ^
      3 warnings and 2 errors generated when compiling for gfx1030.
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
          subprocess.run(
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/pfs/lustrep4/users/kazakose/flash-attention/setup.py", line 312, in <module>
          setup(
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 843, in build_extensions
          build_ext.build_extensions(self)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
          objects = self.compiler.compile(
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 658, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1574, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash-attn
  Running setup.py clean for flash-attn
Failed to build flash-attn
ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects
```

The sentence `3 warnings and 2 errors generated when compiling for gfx1030.` suggests that the GPU environmental variable that I have set is not being used properly. So that might be the issue. Any help would be appreciated!

**Comment by xxtars** [comment]
Hello, I have the same issue. Could you tell me how you resolved this problem? Thank you!
